version: "3.8"

services: 
    web:
        build:
            context: ./services/web
            dockerfile: Dockerfile.devel
        command: python  wsgi.py
        volumes:
            - ./services/web:/opt/app
        ports:
            - 8080:5000
        env_file:
            - ./.env.sqlite
        environment:
            - FLASK_ENV=development
