services:
    web:
        build:
            context: ./services/web
            dockerfile: Dockerfile
            tags: 
                - wheelsofhope:latest
                - angelo53/wheelsofhope:latest
        container_name: wheelsofhope
        command: >-
                  gunicorn --worker-class gthread --workers 4
                  --bind 0.0.0.0:10000 wsgi:app
                  --access-logfile /home/flasker/web/logs/gunicorn-access.log
                  --error-logfile /home/flasker/web/logs/gunicorn-error.log
        ports:
            - 5000:10000
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - upld_vol:/home/flasker/web/uploaded
        env_file:
            - ./.env.pg
        environment:
            - FLASK_ENV=production

volumes:
    upld_vol:

networks:
    ntw_1:
        name: bridge
        external: true

