services:
    web:
        build:
            context: ./services/web
            dockerfile: Containerfile
            tags: 
                - angelo53/amptours:latest
        image: ghcr.io/amp53notpam/amptours
        container_name: amptours
        command: >-
                  gunicorn --worker-class gthread --workers 2
                  --bind 0.0.0.0:10000 wsgi:app
                  --access-logfile /home/flasker/web/logs/gunicorn-access.log
                  --error-logfile /home/flasker/web/logs/gunicorn-error.log
                  --timeout 60
        ports:
            - 5000:10000
        extra_hosts:
            - "host.container.internal:host-gateway"
        volumes:
            - upld_vol:/home/flasker/web/uploaded
        networks:
            - ntw
        env_file:
            - ./.env.pg.render
        environment:
            - FLASK_ENV=production

volumes:
    upld_vol:

networks:
    ntw:
