version: "3.8"

services:
    web:
        build:
            context: ./services/web
            dockerfile: Dockerfile.prod
        command: >-
                  gunicorn --worker-class gthread --workers 4
                  --bind 0.0.0.0:5000 wsgi:app
                  --access-logfile /home/flasker/web/logs/gunicorn-access.log
                  --error-logfile /home/flasker/web/logs/gunicorn-error.log

        volumes:
            - static_vol_1:/home/flasker/web/berlin_tour/static
        ports:
            - 8080:5000
        env_file:
            - ./.env.sqlite
        environment:
            - FLASK_ENV=production

volumes:
    static_vol_1:
