version: "3.8"

services:
    web:
        build:
            context: ./services/web
            dockerfile: Dockerfile.prod
        command: >-
            gunicorn --worker-class gthread --workers 4 
                     --bind 0.0.0.0:5000 wsgi:app
                     --access-logfile /home/flasker/web/logs/gunicorn-access.log
                     --error-logfile /home/flasker/web/logs/gunicorn-error.log
        volumes:
            - static_vol_1:/home/flasker/web/berlin_tour/static
        expose:
            - 5000
        env_file:
            - ./.env.prod
        depends_on:
            - db

    db:
        image: postgres:15-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db

    nginx:
        build:
            context: ./services/nginx
            dockerfile: Dockerfile
        volumes:
            - static_vol_1:/home/flasker/web/Berlin_tour/static
        ports:
            - 1337:80
        depends_on:
            - web

volumes:
    postgres_data:
    static_vol_1:
