version: "3.8"

services:
    web:
        build:
            context: ./services/web
            dockerfile: Dockerfile.prod
        command: python wsgi.py
        volumes:
            - static_vol_1:/home/flasker/web/berlin_tour/static
        ports:
            - 8080:5000
        env_file:
            - ./.env.sqlite
        environment:
            - FLASK_ENV=production

volumes:
    static_vol_1:
