"""empty message

Revision ID: 11f816f31fa0
Revises: 806d284a207f
Create Date: 2026-03-23 20:31:29.191326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f816f31fa0'
down_revision = '806d284a207f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
