"""empty message

Revision ID: 256a0a031bfb
Revises: 7816c4e323a2
Create Date: 2024-11-19 23:13:22.947178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256a0a031bfb'
down_revision = '7816c4e323a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_image', schema=None) as batch_op:
        batch_op.drop_constraint('trip_image_img_src_key', type_='unique')
        batch_op.create_unique_constraint('lap_img_uc', ['lap_id', 'img_src'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_image', schema=None) as batch_op:
        batch_op.drop_constraint('lap_img_uc', type_='unique')
        batch_op.create_unique_constraint('trip_image_img_src_key', ['img_src'])

    # ### end Alembic commands ###
