"""empty message

Revision ID: 28790681fa29
Revises: 45917e83ef71
Create Date: 2026-03-21 22:14:35.617727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28790681fa29'
down_revision = '45917e83ef71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poi', sa.String(length=128), nullable=False),
    sa.Column('at_km', sa.Integer(), nullable=True),
    sa.Column('lap_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lap_id'], ['lap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poi')
    # ### end Alembic commands ###
