"""empty message

Revision ID: 28d031cf8efd
Revises: 719f777a6367
Create Date: 2025-02-10 17:37:19.299399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d031cf8efd'
down_revision = '719f777a6367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.alter_column('lap_id',
                               existing_type=sa.INTEGER(),
                               nullable=False)
        batch_op.drop_constraint('hotel_lap_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'lap', ['lap_id'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('hotel_lap_id_fkey', 'lap', ['lap_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('lap_id',
                               existing_type=sa.INTEGER(),
                               nullable=True)

    # ### end Alembic commands ###
