"""empty message

Revision ID: 2fbcb5dc69b9
Revises: 501359571bee
Create Date: 2024-10-12 18:55:58.086315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbcb5dc69b9'
down_revision = '501359571bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_photos', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.drop_column('has_photos')

    # ### end Alembic commands ###
