"""empty message

Revision ID: 325ea6759db7
Revises: 5983b7f1882e
Create Date: 2024-12-01 23:17:20.983231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '325ea6759db7'
down_revision = '5983b7f1882e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lap_id', sa.Integer(), nullable=True),
    sa.Column('media_src', sa.String(length=96), nullable=False),
    sa.Column('media_width', sa.INTEGER(), nullable=False),
    sa.Column('media_height', sa.INTEGER(), nullable=False),
    sa.Column('media_type', sa.Enum('video', 'image', name='media_types'), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('long', sa.FLOAT(), nullable=True),
    sa.Column('caption', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['lap_id'], ['lap.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lap_id', 'media_src', name='lap_media_uc')
    )
    op.drop_table('trip_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lap_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('img_src', sa.VARCHAR(length=96), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('long', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('caption', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('img_width', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('img_height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('img_type', postgresql.ENUM('video', 'image', name='media_enum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lap_id'], ['lap.id'], name='trip_image_lap_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='trip_image_pkey'),
    sa.UniqueConstraint('lap_id', 'img_src', name='lap_img_uc')
    )
    op.drop_table('media')
    # ### end Alembic commands ###
