"""empty message

Revision ID: 347631624d77
Revises: 34d68c9a6d42
Create Date: 2024-07-21 20:04:10.568247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347631624d77'
down_revision = '34d68c9a6d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_constraint('tour_bind_key', type_='unique')
        batch_op.drop_column('bind')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bind', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('tour_bind_key', ['bind'])

    # ### end Alembic commands ###
