"""Added table tour.

Revision ID: 34d68c9a6d42
Revises: 
Create Date: 2024-07-20 23:11:00.496717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d68c9a6d42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('bind', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bind'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_id', sa.Integer()))
        batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tour_id')

    op.drop_table('tour')
    # ### end Alembic commands ###
