"""empty message

Revision ID: 3f8dd9f6c383
Revises: 347631624d77
Create Date: 2024-07-24 16:56:53.826457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8dd9f6c383'
down_revision = '347631624d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_constraint('hotel_lap_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'lap', ['lap_id'], ['id'], ondelete='set null')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('hotel_lap_id_fkey', 'lap', ['lap_id'], ['id'])

    # ### end Alembic commands ###
