"""empty message

Revision ID: 42fe61492035
Revises: 28d031cf8efd
Create Date: 2025-02-11 09:27:02.278905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42fe61492035'
down_revision = '28d031cf8efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_constraint('hotel_tour_id_fkey', type_='foreignkey')
        batch_op.drop_column('tour_id')

    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.drop_column('has_photos')

    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.drop_constraint('phone_number_hotel_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'hotel', ['hotel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('phone_number_hotel_id_fkey', 'hotel', ['hotel_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_photos', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('hotel_tour_id_fkey', 'tour', ['tour_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
