"""empty message

Revision ID: 45917e83ef71
Revises: ae3106086a5d
Create Date: 2026-03-13 22:22:13.213128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45917e83ef71'
down_revision = 'ae3106086a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx', schema=None) as batch_op:
        batch_op.drop_column('caption')

    # ### end Alembic commands ###
