"""empty message

Revision ID: 45c47e0afa9d
Revises: 4878b9744fbc
Create Date: 2025-02-05 10:09:15.083188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c47e0afa9d'
down_revision = '4878b9744fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_number',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('phone', sa.String(length=16), nullable=True),
                    sa.Column('href_phone', sa.String(length=16), nullable=True),
                    sa.Column('hotel_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ondelete='cascade'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_column('href_phone')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('href_phone', sa.VARCHAR(length=16), autoincrement=False, nullable=True))

    op.drop_table('phone_number')
    # ### end Alembic commands ###
