"""empty message

Revision ID: 48a0a31dc646
Revises: a542253c1649
Create Date: 2024-11-19 17:21:31.408908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48a0a31dc646'
down_revision = 'a542253c1649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_image', schema=None) as batch_op:
        batch_op.drop_column('media_type')
        batch_op.drop_column('orientation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orientation', postgresql.ENUM('portrait', 'landscape', name='orientation_enum'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('media_type', postgresql.ENUM('foto', 'video', name='media_type_enum'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
