"""empty message

Revision ID: 501359571bee
Revises: 94b975cf674a
Create Date: 2024-10-11 20:34:02.346842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501359571bee'
down_revision = '94b975cf674a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_image',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('lap_id', sa.Integer(), nullable=True),
                    sa.Column('img_src', sa.String(length=96), nullable=False),
                    sa.Column('date', sa.DATE(), nullable=False),
                    sa.Column('lat', sa.FLOAT(), nullable=True),
                    sa.Column('long', sa.FLOAT(), nullable=True),
                    sa.ForeignKeyConstraint(['lap_id'], ['lap.id'], ondelete='set null'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('img_src')
                    )
    op.drop_table('trip_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_images',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('lap_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('img_src', sa.VARCHAR(length=96), autoincrement=False, nullable=False),
                    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
                    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('long', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['lap_id'], ['lap.id'], name='trip_images_lap_id_fkey', ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id', name='trip_images_pkey')
                    )
    op.drop_table('trip_image')
    # ### end Alembic commands ###
