"""empty message

Revision ID: 517f15a7a7cf
Revises: f06a1844034a
Create Date: 2024-10-10 23:17:47.674206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517f15a7a7cf'
down_revision = 'f06a1844034a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('lap_id', sa.Integer(), nullable=True),
                    sa.Column('img_src', sa.String(length=64), nullable=False),
                    sa.Column('date', sa.DATE(), nullable=False),
                    sa.Column('lat', sa.FLOAT(), nullable=True),
                    sa.Column('long', sa.FLOAT(), nullable=True),
                    sa.ForeignKeyConstraint(['lap_id'], ['lap.id'], ondelete='set null'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_images')
    # ### end Alembic commands ###
