"""empty message

Revision ID: 5b3e9874e3e1
Revises: dd2a81baea18
Create Date: 2024-10-01 19:21:07.629643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3e9874e3e1'
down_revision = 'dd2a81baea18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
