"""empty message

Revision ID: 70981e01d839
Revises: e7387f7777a7
Create Date: 2026-03-05 17:37:54.761114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70981e01d839'
down_revision = 'e7387f7777a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpx',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('gpx', sa.String(length=64), nullable=False),
                    sa.Column('lap_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['lap_id'], ['lap.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.alter_column('gpx', new_column_name='primary_gpx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.alter_column('primary_gpx', new_column_name='gpx')

    op.drop_table('gpx')
    # ### end Alembic commands ###
