"""empty message

Revision ID: 719f777a6367
Revises: 45c47e0afa9d
Create Date: 2025-02-05 15:42:50.457474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719f777a6367'
down_revision = '45c47e0afa9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['href_phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
