"""empty message

Revision ID: 77cb59c7cdab
Revises: 11f816f31fa0
Create Date: 2026-03-27 19:16:05.320004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cb59c7cdab'
down_revision = '11f816f31fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_in_out',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('check_type', sa.Enum('IN', 'OUT', name='checkinout_enum'), nullable=False),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.Column('after', sa.Time(), nullable=True),
                    sa.Column('before', sa.Time(), nullable=True),
                    sa.Column('hotel_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    check_in_out = sa.sql.table('check_in_out',
                                sa.Column('id', sa.Integer(), nullable=False),
                                sa.Column('check_type', sa.Enum('IN', 'OUT', name='checkinout_enum'), nullable=False),
                                sa.Column('date', sa.Date(), nullable=True),
                                sa.Column('hotel_id', sa.Integer(), nullable=False)
                                )
    conn = op.get_bind()
    results = conn.execute(sa.text("select id, check_in from hotel")).fetchall()
    values_in = [{'hotel_id': r[0], 'date': r[1], 'check_type': 'IN'} for r in results]

    results = conn.execute(sa.text("select id, check_out from hotel")).fetchall()
    values_out = [{'hotel_id': r[0], 'date': r[1], 'check_type': 'OUT'} for r in results]

    op.bulk_insert(check_in_out, values_in)
    op.bulk_insert(check_in_out, values_out)

    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_column('check_out')
        batch_op.drop_column('check_in')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('check_out', sa.DATE(), autoincrement=False, nullable=True))

    hotel = sa.sql.table('hotel',
                         sa.Column('id', sa.Integer(), nullable=False),
                         sa.Column('check_in', sa.DATE(), nullable=True),
                         sa.Column('check_out', sa.DATE(), nullable=True)
                         )

    conn = op.get_bind()
    results = conn.execute(sa.text("select hotel_id, date from check_in_out where check_type='IN'")).fetchall()
    values = [{'check_in': r[1], 'id': r[0]} for r in results]
    for value in values:
        op.execute(hotel.update().where(hotel.c.id == value['id'])
                   .values({"check_in": value['check_in']}))

    results = conn.execute(sa.text("select hotel_id, date from check_in_out where check_type='OUT'")).fetchall()
    values = [{'check_out': r[1], 'id': r[0]} for r in results]
    for value in values:
        op.execute(hotel.update().where(hotel.c.id == value['id'])
                   .values({"check_out": value['check_out']}))

    op.drop_table('check_in_out')
    # ### end Alembic commands ###
    conn.execute(sa.text("drop type checkinout_enum"))
