"""new columns in tour and hotel

Revision ID: 7d73a5e98367
Revises: b32bccb2ce78
Create Date: 2025-01-20 15:16:38.533674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d73a5e98367'
down_revision = 'b32bccb2ce78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.BOOLEAN(), nullable=True))
    

    # ### end Alembic commands ###
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM tour")).scalars()
    for i in result:
        op.execute(f"update hotel set tour_id={i} where id in (select hotel.id from hotel join lap on hotel.lap_id = lap.id where lap.tour_id = {i})")
    op.execute("update hotel set tour_id = (select max(id) from tour) where tour_id is null")
    
    op.execute("UPDATE tour SET is_visible = True")

    
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.alter_column('tour_id',
               existing_type=sa.INTEGER(),
               nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_constraint('hotel_tour_id_fkey', type_='foreignkey')
        batch_op.drop_column('tour_id')

    # ### end Alembic commands ###
