"""empty message

Revision ID: 806d284a207f
Revises: 28790681fa29
Create Date: 2026-03-22 22:39:56.640844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806d284a207f'
down_revision = '28790681fa29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.alter_column('at_km',
                              existing_type=sa.INTEGER(),
                              type_=sa.Float(),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.alter_column('at_km',
                              existing_type=sa.Float(),
                              type_=sa.INTEGER(),
                              existing_nullable=True)

    # ### end Alembic commands ###
