"""empty message

Revision ID: 8309171541c0
Revises: 7d73a5e98367
Create Date: 2025-01-27 18:56:00.532519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8309171541c0'
down_revision = '7d73a5e98367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.create_unique_constraint('tour_lap_at_date_uc', ['tour_id', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.drop_constraint('tour_lap_at_date_uc', type_='unique')

    # ### end Alembic commands ###
