"""empty message

Revision ID: 8979505145a0
Revises: 77a425786717
Create Date: 2025-02-14 16:56:41.954749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8979505145a0'
down_revision = '77a425786717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.alter_column('gpx',
               existing_type=sa.VARCHAR(length=48),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.alter_column('gpx',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=48),
               existing_nullable=True)

    # ### end Alembic commands ###
