"""empty message

Revision ID: 8a9671216619
Revises: 256a0a031bfb
Create Date: 2024-11-27 11:03:47.392414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9671216619'
down_revision = '256a0a031bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_width', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('img_height', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_image', schema=None) as batch_op:
        batch_op.drop_column('img_height')
        batch_op.drop_column('img_width')

    # ### end Alembic commands ###
