"""empty message

Revision ID: 94ac7762b8ff
Revises: 240f75ba2413
Create Date: 2024-11-14 21:11:37.811876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ac7762b8ff'
down_revision = '240f75ba2413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carousel_pos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_column('carousel_pos')

    # ### end Alembic commands ###
