"""empty message

Revision ID: a542253c1649
Revises: c8158347f068
Create Date: 2024-11-18 23:06:57.718425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a542253c1649'
down_revision = 'c8158347f068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.Enum('foto', 'video', name='media_type_enum'), nullable=False))
        batch_op.alter_column('orientation',
               existing_type=postgresql.ENUM('portrait', 'landscape', name='orientation_enum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_image', schema=None) as batch_op:
        batch_op.alter_column('orientation',
               existing_type=postgresql.ENUM('portrait', 'landscape', name='orientation_enum'),
               nullable=True)
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
