"""empty message

Revision ID: a96bea750260
Revises: 77cb59c7cdab
Create Date: 2026-04-10 11:54:06.754056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96bea750260'
down_revision = '77cb59c7cdab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel_id', sa.Integer(), nullable=True))
        batch_op.alter_column('lap_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.create_foreign_key(None, 'hotel', ['hotel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx', schema=None) as batch_op:
        batch_op.drop_constraint('gpx_hotel_id_fkey', type_='foreignkey')
        batch_op.drop_column('hotel_id')

    # ### end Alembic commands ###
