"""empty message

Revision ID: ae3106086a5d
Revises: 70981e01d839
Create Date: 2026-03-05 19:18:28.692956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3106086a5d'
down_revision = '70981e01d839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx', schema=None) as batch_op:
        batch_op.create_unique_constraint('lap_gpx_uc', ['lap_id', 'gpx'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx', schema=None) as batch_op:
        batch_op.drop_constraint('lap_gpx_uc', type_='unique')

    # ### end Alembic commands ###
