"""empty message

Revision ID: b32bccb2ce78
Revises: f58578622ac4
Create Date: 2025-01-11 19:29:30.369233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32bccb2ce78'
down_revision = 'f58578622ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_caption', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_column('pic_caption')

    # ### end Alembic commands ###
