"""empty message

Revision ID: beafcc565b2a
Revises: 8979505145a0
Create Date: 2025-02-16 23:48:48.971984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beafcc565b2a'
down_revision = '8979505145a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_constraint('hotel_lap_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'lap', ['lap_id'], ['id'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('lap_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.drop_constraint('media_lap_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'lap', ['lap_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('media_lap_id_fkey', 'lap', ['lap_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('lap_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)

    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('hotel_lap_id_fkey', 'lap', ['lap_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
