"""empty message

Revision ID: c237d007faa5
Revises: 251f155afff8
Create Date: 2025-01-09 16:23:26.058868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c237d007faa5'
down_revision = '251f155afff8'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('tour_owner_id_fkey', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    ## with op.batch_alter_table('tour', schema=None) as batch_op:
        ## batch_op.alter_column('owner_id',
               ## existing_type=sa.INTEGER(),
               ## nullable=False)
        ## batch_op.drop_constraint('tour_owner_id_fkey', type_='foreignkey')
        ## batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tour_owner_id_fkey', 'user', ['owner_id'], ['id'])
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
