"""empty message

Revision ID: c8158347f068
Revises: 94ac7762b8ff
Create Date: 2024-11-18 19:34:09.291831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8158347f068'
down_revision = '94ac7762b8ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orientation', sa.Enum('portrait', 'landscape', name='orientation_enum'), nullable=True))
        batch_op.add_column(sa.Column('caption', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_image', schema=None) as batch_op:
        batch_op.drop_column('caption')
        batch_op.drop_column('orientation')

    # ### end Alembic commands ###
