"""empty message

Revision ID: ce198d01290b
Revises: 2fbcb5dc69b9
Create Date: 2024-10-28 14:18:34.131311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce198d01290b'
down_revision = '2fbcb5dc69b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('trip_mode', sa.Enum('walking', 'bicycling', 'driving', name='mode_enum'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
