"""empty message

Revision ID: dd2a81baea18
Revises: 31c88064c9f5
Create Date: 2024-07-28 14:12:34.142651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2a81baea18'
down_revision = '31c88064c9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.drop_constraint('lap_date_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.create_unique_constraint('lap_date_key', ['date'])

    # ### end Alembic commands ###
