"""empty message

Revision ID: de6d7077e675
Revises: bfcce9ee0cd7
Create Date: 2025-03-14 15:18:31.397972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6d7077e675'
down_revision = 'bfcce9ee0cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=48),
                              type_=sa.String(length=64),
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.String(length=64),
                              type_=sa.VARCHAR(length=48),
                              existing_nullable=False)

    # ### end Alembic commands ###
