"""empty message

Revision ID: e324bc53c0bb
Revises: a96bea750260
Create Date: 2026-04-12 19:52:25.567739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e324bc53c0bb'
down_revision = 'a96bea750260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx', schema=None) as batch_op:
        batch_op.alter_column('caption',
                              existing_type=sa.VARCHAR(length=32),
                              type_=sa.String(length=64),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpx', schema=None) as batch_op:
        batch_op.alter_column('caption',
                              existing_type=sa.String(length=64),
                              type_=sa.VARCHAR(length=32),
                              existing_nullable=True)

    # ### end Alembic commands ###
