"""empty message

Revision ID: e4964eceb320
Revises: 325ea6759db7
Create Date: 2025-01-03 22:15:16.823771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4964eceb320'
down_revision = '325ea6759db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_pic', sa.String(length=96), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_column('trip_pic')

    # ### end Alembic commands ###
