"""empty message

Revision ID: ef6b71e9db83
Revises: beafcc565b2a
Create Date: 2025-02-26 12:01:55.418669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6b71e9db83'
down_revision = 'beafcc565b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.alter_column('phone',
                              existing_type=sa.VARCHAR(length=16),
                              type_=sa.String(length=24),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.alter_column('phone',
                              existing_type=sa.String(length=24),
                              type_=sa.VARCHAR(length=16),
                              existing_nullable=True)

    # ### end Alembic commands ###
