"""empty message

Revision ID: f58578622ac4
Revises: 1c3e993f8206
Create Date: 2025-01-11 18:17:56.047046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58578622ac4'
down_revision = '1c3e993f8206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_constraint('tour_name_key', type_='unique')
        batch_op.create_unique_constraint('name_mode_uc', ['name', 'trip_mode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_constraint('name_mode_uc', type_='unique')
        batch_op.create_unique_constraint('tour_name_key', ['name'])

    # ### end Alembic commands ###
